create database testetrigger;

use testetrigger;

CREATE TABLE TABFUN ( /* Tabela de funcionários */
    IDFUN INT AUTO_INCREMENT PRIMARY KEY,
    NOMEFUN VARCHAR(40) NOT NULL,
    CPF NUMERIC(12),
    DATAADM DATE,
    SALARIO DECIMAL(10,2)
);

CREATE TABLE TABLOG ( /* Registro das atividades */
    ID INT,
    USUARIO VARCHAR(40),
    ACAO VARCHAR(15),
    DATA DATE,
    HORA TIME,
    salantes decimal(10,2),
    saldepois decimal(10,2)
);


CREATE trigger G_LOG1 AFTER INSERT ON TABFUN
FOR EACH ROW
    INSERT INTO TABLOG
    SET ID=NEW.IDFUN,
    USUARIO=USER(),
    ACAO='INSERIU',
    DATA=CURDATE(),
    HORA=CURTIME();

CREATE trigger G_LOG2 BEFORE DELETE ON TABFUN
FOR EACH ROW
    INSERT INTO TABLOG
    SET ID=OLD.IDFUN,
    USUARIO=USER(),
    ACAO='EXCLUIU',
    DATA=CURDATE(),
    HORA=CURTIME();

CREATE trigger G_LOG3 BEFORE UPDATE ON TABFUN
FOR EACH ROW
    INSERT INTO TABLOG
    SET ID=NEW.IDFUN,
    USUARIO=USER(),
    ACAO='ALTEROU',
    DATA=CURDATE(),
    HORA=CURTIME();

CREATE trigger G_LOG4 AFTER UPDATE ON TABFUN
FOR EACH ROW
    INSERT INTO TABLOG
    SET ID=NEW.IDFUN,
    USUARIO=USER(),
    acao='ALTEROU',
    DATA=CURDATE(),
    HORA=CURTIME(),
    SALANTES=OLD.SALARIO,
    SALDEPOIS=NEW.SALARIO;