CREATE DATABASE EMPRESA;
USE EMPRESA;
CREATE TABLE DEPTO(
  DEPTNO INT AUTO_INCREMENT PRIMARY KEY,
  DNOME VARCHAR(20) NOT NULL);

CREATE TABLE EMP(
   EMPNO INT AUTO_INCREMENT PRIMARY KEY,
   ENOME VARCHAR(40) NOT NULL,
   ESAL DECIMAL(6,2) NOT NULL,
   EDATADM DATE,
   EFUNCAO CHAR(12) NOT NULL,
   DEPTNO INT,
   FOREIGN KEY (DEPTNO) REFERENCES DEPTO(DEPTNO) );

CREATE TABLE FONES_EMP(
   EMPNO INT,
   EFONE CHAR(12),
   PRIMARY KEY(EMPNO,EFONE),
   FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO));
   
/* DADOS */

INSERT INTO DEPTO (DNOME) VALUES ('VENDAS'),('COMPRAS'),('RH');

INSERT INTO EMP (ENOME, ESAL, EFUNCAO, DEPTNO) VALUES

('RENATO',5000,'ANALISTA',2),

('MANUEL',3500,'PROGRAMADOR',2),

('VALTER',6000,'GERENTE',3),

('ADALBERTO',4000,'GERENTE',2),

('JULIO',3800,'ANALISTA',3);

INSERT INTO FONES_EMP VALUES

(1,'44430000'), (1,'997766554'),

(3,'44430000'),(3,'987654321'),

(5,'912345678');

SELECT * FROM DEPTO;

SELECT * FROM EMP;

SELECT * FROM FONES_EMP;